apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  version: v1.29.3+k3s1
  nodeSelector:
    matchLabels:
      k3s-upgrade: server
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  concurrency: 2
  version: v1.29.3+k3s1
  nodeSelector:
    matchLabels:
      k3s-upgrade: agent
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
